version: '3.5'

services:
    server:
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile-web
        working_dir: /srv/app/server
        env_file: .dockerenv
        command: ./manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        networks:
            app_net:
                ipv4_address: 172.32.1.1
                aliases:
                    - crh-server-net
    celery:
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile-web
        working_dir: /srv/app/server
        env_file: .dockerenv
        command: python3 celery.py
        networks:
            app_net:
                ipv4_address: 172.32.1.2
                aliases:
                    - crh-celery-net
    client:
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile-client
        working_dir: /srv/app/client
        env_file: .dockerenv
        networks:
            app_net:
                ipv4_address: 172.32.1.3
                aliases:
                    - crh-client-net
    db:
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile-db
        env_file: .dockerenv
        networks:
            app_net:
                ipv4_address: 172.32.1.4
                aliases:
                    - crh-db-net

volumes:
    db-volume:
        name: christian-hall_db-volume
    static-volume:
        name: christian-hall_static-volume
    python-packages:
        name: christian-hall_python-packages

networks:
    app_net:
        name: crh-net
        driver: bridge
        ipam:
            config:
                - subnet: 172.32.0.0/24
