version: '3.5'

services:
    server:
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile-server
        env_file: .dockerenv
        working_dir: /srv/app/server
        user: ${UID:-1000}
        environment:
            DEBUG: 'true'
        command: ./manage.py runserver 0.0.0.0:8004
        ports:
            # local:docker
            - "8004:8000"
        volumes:
            - ".:/srv/app:delegated"
            - "static-volume:/srv/app/static:z"
            - "python-packages:/usr/local/lib/python3.10/site-packages:z"
        networks:
            app_net:
                ipv4_address: 172.32.1.1
                aliases:
                    - crh-server-net
    client:
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile-client
        env_file: .dockerenv
        working_dir: /srv/app/client
        volumes:
            - "./client:/srv/app/client:delegated"
            - "static-volume:/srv/app/static:z"
        networks:
            app_net:
                ipv4_address: 172.32.1.2
                aliases:
                    - crh-client-net
    db:
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile-db
        environment:
            POSTGRES_USER: crhall
            POSTGRES_PASSWORD: crhall
            POSTGRES_DB: crhall
            PG_DATA: /var/lib/postgresql/data/pgdata
        ports:
            # local:docker
            - "5433:5432"
        volumes:
            - "db-volume:/var/lib/postgresql/data/pgdata"
        networks:
            app_net:
                ipv4_address: 172.32.1.3
                aliases:
                    - crh-db-net

volumes:
    db-volume:
        name: christian-hall_db-volume
    static-volume:
        name: christian-hall_static-volume
    python-packages:
        name: christian-hall_python-packages

networks:
    app_net:
        name: crh-net
        driver: bridge
        ipam:
            config:
                - subnet: 172.32.0.0/16
