FROM node:12.0.0

USER root
# check first which npm it comes
#RUN yarn global add npm@12.22.8
#RUN npm install -g lerna@2.5.1

USER node
WORKDIR /srv/app
RUN chown node.node /srv/app
COPY --chown=node:node client client

WORKDIR shared
USER node
RUN npm run lerna -- bootstrap

# vim:set ft=dockerfile:
