FROM nginx:1.17.4

#RUN apk update && apk add bash

RUN apt-get update && apt-get --yes install \
    # ps
    procps \
    # netstat
    net-tools \
    vim \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf


#USER node
#WORKDIR /srv/app/client
#RUN npm run build


#USER root

# start bash shell
#RUN /bin/bash
