FROM postgres:10.6

# Notes
# Login to db: `psql -d crhall -U crhall`

RUN apt-get update && apt-get --yes install \
    postgresql-contrib-10 \
    postgresql-10-postgis-2.5 \
    postgresql-10-postgis-2.5-scripts \
    # netstat, etc.
    net-tools \
    vim \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Switch to user line to 'root' to get root access on bash connect (`docker-compose exec db bash`)
USER postgres



#RUN /etc/init.d/postgresql start
#RUN psql --command "CREATE USER crhall WITH SUPERUSER PASSWORD 'crhall';"
#RUN createdb -O crhall crhall
#
#RUN echo "host all  all     0.0.0.0/0 md5" >> /etc/postgresql/10/main/pg_hba.conf
#
#RUN echo "listen_addresses='*'" >> /etc/postgresql/10/main/postgresql.conf
#
EXPOSE 5432
#
## /var/lib/postgresql
#
#CMD ["/usr/lib/postgresql/10/bin/postgres", "-D", "/var/lib/postgresql/10/main", "-c", "config_file=/etc/postgresql/10/main/postgresql.conf"]

# vim:set ft=dockerfile:
