FROM postgres:10.6
RUN apt-get update && apt-get --yes install \
    postgresql-contrib-10 \
    postgresql-10-postgis-2.5 \
    postgresql-10-postgis-2.5-scripts \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# vim:set ft=dockerfile:
