FROM node:8.8.1

RUN yarn global add npm@5.5.1
RUN npm install -g lerna@2.5.1
WORKDIR /srv/app
RUN chown node.node /srv/app
COPY --chown=node:node shared shared
COPY --chown=node:node client client
COPY --chown=node:node server/locale server/locale
WORKDIR shared
USER node
RUN npm run lerna -- bootstrap

# vim:set ft=dockerfile:
