FROM nginx:1.17.4

#RUN apk update && apk add bash

RUN apt-get update && apt-get --yes install \
    procps \    # ps
    net-tools \  # netstat
    vim \       # file edit
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d


#USER node
#WORKDIR /srv/app/client
#RUN npm run build


USER root

# start bash shell
#RUN /bin/bash
