#!/bin/bash

# docker-compose exec server bash

set -e
SCRIPT_BASE=$(dirname "$0")

echo Script Base: $SCRIPT_BASE

source $SCRIPT_BASE/utils

ROOT=$(resolve_path "$SCRIPT_BASE/..")
echo root path: $ROOT


target=server

POSITIONAL=()
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -t|--target)
            target=$2
            shift
            ;;
        -h|--help|?)
            echo "Launch an interactive console on the appropriate service."
            echo
            cecho "Usage: $(basename "$0") [<CONSOLE TYPE>]" default bold
            echo
            echo "Console Types:"
            echo "  bash         - Bash (Default)"
            echo "  sudo         - Bash as sudo"
            echo "  py  | python - Django Shell Plus w/ IPython"
            echo "  sql | psql   - PostgreSQL as root"
            echo
            echo "Options:"
            echo "  -h  --help          This help message"
            echo "  -t  --target        Choose which service to connect to for 'bash' or 'sudo' consoles (default: server)"
            echo
            echo "Environment Variables:"
            echo "  PROD=0              Development setup: docker-compose.yml (default)"
            echo "  PROD=1              Production setup: docker-compose-prod.yml"
            exit 0
            ;;
        *)
            POSITIONAL+=("$key")
            ;;
    esac
    shift
done
set -- "${POSITIONAL[@]}"

# Default to development environment
PROD=${PROD:-0}

if [ "$1" ]; then
    shell=$1
else
    shell="bash"
fi

echo \*\* Shell: $shell
echo \*\* Target: $target

case $shell in
    bash)
        cmd="$target bash"
        ;;
    sudo)
        cmd="-u root $target bash"
        ;;
    py|python)
        cmd="server ./manage.py shell"
        #cmd="server ./manage.py shell_plus"
        ;;
    sql|psql)
        cmd="-u root db psql -U crhall crhall"
        ;;
    redis)
        cmd="redis redis-cli"
        ;;
    vue)
        cmd="vue bash"
        ;;
    *)
        cecho "You must provide a valid shell type. Please see '$(basename "$0") --help' for more information." red bold
        exit 1
        ;;
esac

# shellcheck disable=SC2086 # Intended splitting of cmd
COLUMNS="$(tput cols)" LINES="$(tput lines)" docker_compose exec $cmd
