#!/bin/bash

# docker-compose exec --target client eslint --ext .js,.ts,.vue ./

set -e
SCRIPT_BASE=$(dirname "$0")

echo Script Base: $SCRIPT_BASE

source $SCRIPT_BASE/utils

ROOT=$(resolve_path "$SCRIPT_BASE/..")
echo root path: $ROOT


target=client
fix=0

POSITIONAL=()
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -t|--target)
            target=$2
            shift
            ;;
        -f|--fix)
            fix=1
            shift
            ;;
        -h|--help|?)
            echo "Launch an interactive console on the appropriate service."
            echo
            cecho "Usage: $(basename "$0") [<CONSOLE TYPE>]" default bold
            echo
            echo "Lint Checks:"
            echo "  eslint"
            echo "  python (not implemented)"
            echo
            echo "Options:"
            echo "  -h  --help          This help message"
            echo "  -t  --target        Choose which service to connect to for linting (default: client)"
            echo "  -f  --fix           Automatically fix eslint errors if possible"
            echo
            echo "Environment Variables:"
            echo "  PROD=0              Development setup: docker-compose.yml (default)"
            echo "  PROD=1              Production setup: docker-compose-prod.yml"
            exit 0
            ;;
        *)
            POSITIONAL+=("$key")
            ;;
    esac
    shift
done
set -- "${POSITIONAL[@]}"

# Default to development environment
PROD=${PROD:-0}

if [ "$fix" = 1 ]; then
    cmd="npm run lintfix"
else
    cmd="npm run lint"
fi

# shellcheck disable=SC2086 # Intended splitting of cmd
COLUMNS="$(tput cols)" LINES="$(tput lines)" docker_compose exec $target $cmd
