#!/bin/bash

# Examples:
#   ./docker-scripts/manage showmigrations
#   ./docker-scripts/manage --user 
#   ./docker-scripts/manage -c root


set -e
SCRIPT_BASE=$(dirname "$0")
cd $SCRIPT_BASE/..

source $SCRIPT_BASE/utils


create_user=0
change_pass=0

POSITIONAL=()
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -u|--user)
            create_user=1
            ;;
        -c|--change)
            change_pass=1
            ;;
        -h|--help|?)
            echo "Run Django manage.py command with arguments."
            echo
            cecho "Usage: $(basename $0) [COMMAND] <options> [args...]" default bold
            echo
            echo "Commands:"
            echo "  [<args>...]         Run any manage.py command inside docker for development."
            echo
            echo "Options:"
            echo "  -u  --user          Runs createsuperuser prompt."
            echo "  -c  --change        Change superuser password."
            echo "  -h  --help          This help message"
            exit 0
            ;;
        *)
            POSITIONAL+=("$1")
            ;;
    esac
    shift
done
set -- "${POSITIONAL[@]}"

case $create_user in
    1)
        get_docker_compose exec server ./manage.py createsuperuser
        ;;
    ?)
        ;;
esac

if [[ "$change_pass" == 1 ]]; then
    get_docker_compose exec server ./manage.py changepassword $@
fi



if [[ "$create_user" == 0 && "$change_pass" == 0 ]]; then
    get_docker_compose exec server ./manage.py $@
fi

# TODO: ensure migrate runs on setup, not just update
# TODO: after migrate is run, create default superuser

# ./docker-scripts/manage createsuperuser
# ./docker-scripts/manage startapp accounts
