#!/bin/bash

set -e
SCRIPT_BASE=$(dirname "$0")
cd $SCRIPT_BASE/..

source $SCRIPT_BASE/utils

detach=

POSITIONAL=()
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -d|--detach)
            detach=1
            ;;
        -h|--help|?)
            echo "Rebuild, create, run and attach all or specfic Docker services."
            echo
            cecho "Usage: $(basename $0) <options> [SERVICE...]" default bold
            echo
            echo "Options:"
            echo "  -d  --detach        Detached mode: Run containers in background."
            echo "  -h  --help          This help message"
            echo
            echo "Environment Variables:"
            echo "  PROD=0              Development setup: docker-compose.yml (default)"
            echo "  PROD=1              Production setup: docker-compose-prod.yml"
            echo
            echo "Run 'docker-compose up --help' to see more options"
            exit 0
            ;;
        *)
            POSITIONAL+=("$key")
            ;;
    esac
    shift
done
set -- "${POSITIONAL[@]}"

# Default to development environment
PROD=${PROD:-0}

#if [ ! "$(docker network ls | grep crh-net)" ]; then
#    cecho "Shared network not found, creating..." yellow bold
#    docker network create --driver=bridge --subnet=172.32.0.0/16 crh-net
#fi

args=$@

stop_first() {
    $SCRIPT_BASE/stop $args
}
trap "stop_first" INT

docker_compose up -d $args

if [ "$detach" ]; then
    cecho "Starting in detached mode. Use '$SCRIPT_BASE/attach <service>' to view output." blue bold
else
    docker_compose logs --tail 1000 -f $args || teardown
fi
