#!/bin/bash

set -e
script_base=$(dirname "$0")
cd $script_base/..

source $script_base/utils

POSITIONAL=()
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -h|--help|?)
            echo "Stop all or specfic running Docker services."
            echo
            cecho "Usage: $(basename $0) [SERVICE...]" default bold
            echo
            echo "Environment Variables:"
            echo "  PROD=0              Development setup: docker-compose.yml (default)"
            echo "  PROD=1              Production setup: docker-compose-prod.yml"
            exit 0
            ;;
        *)
            POSITIONAL+=("$1")
            ;;
    esac
    shift
done
set -- "${POSITIONAL[@]}"

# Default to development environment
PROD=${PROD:-0}

docker_compose stop $@
