#!/bin/bash

set -e
script_base=$(dirname "$0")
cd $script_base/..

source $script_base/utils

POSITIONAL=()
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -h|--help|?)
            echo "Stop all or specfic running Docker services."
            echo
            cecho "Usage: $(basename $0) [SERVICE...]" default bold
            exit 0
            ;;
        *)
            POSITIONAL+=("$1")
            ;;
    esac
    shift
done
set -- "${POSITIONAL[@]}"

echo Test $@
docker-compose stop $@
