#!/bin/bash
set -e
script_base=$(dirname "$0")
cd $script_base/../..

source $script_base/../tools

port=5555
detach=

POSITIONAL=()
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -d|--detach)
            detach=-d
            ;;
        -p|--port)
            port=$2
            shift
            ;;
        -h|--help|?)
            if [ "$2" != "quiet" ]; then
                echo "A web-based tool for monitoring and administration Celery"
                echo
                cecho "Usage: run_util $(basename $0) <options>" default bold
                echo
            else
                echo "flower"
                echo "------"
                echo "flower - A web-based tool for monitoring and administration Celery"
            fi
            echo "Options:"
            echo "  -p  --port         Port to bind"
            exit 0
            ;;
        *)
            POSITIONAL+=("$key")
            ;;
    esac
    shift
done
set -- "${POSITIONAL[@]}"

cecho "Be sure to set FLOWER_PORT in your .env file to expose on non-random port" yellow bold
docker-compose exec $detach celery sh -c "celery flower --broker=redis://sk-redis:6379/2 --app sk"
